services:
  bbc-news:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbc-news-app
    ports:
      - "8000:8000"
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"